version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "09:00"
      timezone: America/Denver
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "09:00"
      timezone: America/Denver
    open-pull-requests-limit: 3
